### ISSUE TITLE
Put some padding for unique value legend

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#1155]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/2639701/212406464-44c636aa-0e65-4c24-9d1c-24c1df8b2520.png">

**Comment by Thuhaa** [comment]
Closing this as it was already handled by [69443ef](https://github.com/UNDP-Data/geohub/commit/69443efaad46839d6ab482c3300cfb34730f7df2)
