### ISSUE TITLE
[BUG] The bottom of screen is not shown in smartphone (iOS)

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#1207]
### Bug Description

The bottom of screen does not show in smartphone in GeoHub and dashboard

### Bug Reproduction

Access dev.undpgeohub.org from iOS

### Bug Expected Behavior

show all information properly without hiding the bottom

### Bug Actual Behavior

see bug description

### Bug Screenshots

![image](https://user-images.githubusercontent.com/2639701/214336970-2c4b47f2-aa0f-4341-8c80-44c6e15208a6.png)

### Bug System Information

- OS: iOS
- Browser: Safari, Chrome

**Comment by Thuhaa** [comment]
Also doen't show on Android.
Browser: Chrome
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45137948/214339440-3c872bb0-e912-4559-8665-3b6b09b1b384.png)

**Comment by JinIgarashi** [comment]
dashboard page is shown properly in iOS now, but main page's map still does not show the bottom of page.
