### ISSUE TITLE
replace simple/advanced with Default/Classify labels in in all components

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#1217]
### Feature Description

We decided together to replace the toggle button with two buttons in order to  switch the legend/view for a given layer

**Comment by JinIgarashi** [comment]
rename both vector and raster components to be similar one (https://github.com/UNDP-Data/geohub/pull/1235#pullrequestreview-1271558239)

- existing one

|raster|vector|
|---|---|
|RasterLegendContainer|VectorLegendPanel|
|RasterAdvancedLegend|VectorLegendAdvanced|
|RasterExpression|VectorFilterPanelWizard|
|RasterContinuousLegend|VectorLine, VectorPolygon, VectorSymbol|

- new one (proposed)

|raster|vector|
|---|---|
|RasterLegend|VectorLegend|
|RasterClassifyLegend|VectorClassifyLegend|
|RasterFilter|VectorFilter|
|RasterDefaultLegend|VectorLine, VectorPolygon, VectorSymbol|

note, existing `RasterFilter` component seems not being used. we may delete it.
