### ISSUE TITLE
[BUG] restoring parameters from saved map seems not working

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#1292]
### Bug Description

restoring parameters from saved map seems not working

### Bug Reproduction

- change parameter in funciton layer
- save map
- reload browser
- change tab to parameter
- looks all settings are reverted

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by iferencik** [comment]
@JinIgarashi , i am fetching the layerURL from a function layer nad somehow, is foudn out is is set to the wrong value when the map is restored


for example on direct load the url is 

[https://pgtileserv.undpgeohub.org/admin.hdi_subnat_extarg/{z}/{x}/{y}.pbf](https://pgtileserv.undpgeohub.org/admin.hdi_subnat_extarg/{z}/{x}/{y}.pbf)


while on map reload is

[/api/vector/pgtileserv/tile.json?table=admin.hdi_subnat_extarg&type=function](/api/vector/pgtileserv/tile.json?table=admin.hdi_subnat_extarg&type=function)

This is why it fails

**Comment by iferencik** [comment]
The  layer function url is not set correctly in the saved style

![image](https://user-images.githubusercontent.com/92793531/217109354-0863ad18-f98b-48dd-a271-bdd116d7081e.png)
