### ISSUE TITLE
[FEATURE] proposed sidebar of GeoHub

### ISSUE THREAD

**Issue by rafdouglas** [UNDP-Data/geohub#1330]
### Feature Description

In responsive mode, it seems is not clear to everyone how to collapse/reopen the side-tab.

### Feature Implementation

![sidetab_mockup](https://user-images.githubusercontent.com/18248460/217279842-e73d48c6-5702-4211-a93f-5b1e0a887c44.png)

it is proposed to:

- show part of the map under the open side-tab (to convey the idea that there is something else to see, other than the tab itself), ideally on three sides of the tab.
- Make the tab collapsable by dragging it to the left (into a thin, semi-transparent vertical bar).
- Make it possible to re-open it by dragging to the right the thin vertical bar.

### Feature Alternatives

An option would be to use an "x" mark on top right to close the side tab. 
That would create a new floating icon, which opens the tab again upon clicking.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201767552) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
I just found this svelte library. maybe it can be used for GeoHub sidebar

https://github.com/Anyass3/sidebar-swipe

**Comment by JinIgarashi** [comment]
Also, we may implement my menu plugin to Geohub itself. This menu plugin is currently used in electricity dashboard

https://github.com/watergis/svelte-maplibre-components/tree/main/packages/menu
