### ISSUE TITLE
[BUG] colormap name is not restored from saved map

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#1340]
### Bug Description

colormap name is not restored from saved map for raster

### Bug Reproduction

open following saved map.

https://dev.undpgeohub.org/?style=132#1.46/33.1/11.5

### Bug Screenshots

<img width="541" alt="image" src="https://user-images.githubusercontent.com/2639701/217539275-631dd257-934e-4ca4-8814-5c5eff429812.png">

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by JinIgarashi** [comment]
even vector map too

<img width="463" alt="image" src="https://user-images.githubusercontent.com/2639701/217539815-72952282-b836-4074-aeaa-5032f2cadc9d.png">

https://dev.undpgeohub.org/?style=98#5.75/-13.202/27.853

**Comment by JinIgarashi** [comment]
I think we can also solve the issue of `colorMapName` property in Layer object at the same time with solving this issue.

in previous code, if colormap name is changed, it fire `colormap:changed` maplibre event to save colormap name in share dialog.

if you search `colormap:changed` in vscode, you can find four files fire this custom event.

![image](https://user-images.githubusercontent.com/2639701/217541988-0f196cb4-9abc-424e-933d-71b5724bd95d.png)

share dialog is going to save both $layerList and current style.json. If we can correctly store state of colorMapName in Layer object, we don't need to do additional configurations on saved style.json and restore legend state from saved style.json in +page.server.ts.

https://github.com/UNDP-Data/geohub/blob/2bf5354130a72ad6388d70a72a6dcef4c4a991e2/sites/geohub/src/components/StyleShare.svelte#L78-L106

https://github.com/UNDP-Data/geohub/blob/2bf5354130a72ad6388d70a72a6dcef4c4a991e2/sites/geohub/src/routes/%2Bpage.server.ts#L28-L38

**Comment by JinIgarashi** [comment]
Actually, colormap name is saved `viridis` in saved style as shown in the below figure. Probably, legend state management was broken since `colormapName` and `classificaiton method` were added to Layer object.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/2639701/217544119-99e588ea-2348-4367-b7c7-692d2125cf3c.png">

**Comment by iferencik** [comment]
> Actually, colormap name is saved `viridis` in saved style as shown in the below figure. Probably, legend state management was broken since `colormapName` and `classificaiton method` were added to Layer object.
> 
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/2639701/217544119-99e588ea-2348-4367-b7c7-692d2125cf3c.png">

No. they were not. Those two properties were added but not used. I panned to use them in refactoring later

**Comment by JinIgarashi** [comment]
@iferencik this issue was solved by PR https://github.com/UNDP-Data/geohub/pull/1350. I think now we can close it

**Comment by Thuhaa** [comment]
Closing as it is already fixed
