### ISSUE TITLE
 [BUG] Metadata information update fault for two data sets

### ISSUE THREAD

**Issue by s6sapolw** [UNDP-Data/geohub#1481]
### Bug Description

I have tried to update the metadata for the following two data sets and even after the update the license information is not updated.
Image 1 : before updating ![image](https://user-images.githubusercontent.com/101448516/223135970-202adeca-80e6-46a0-9eda-f0134b6025d6.png)
Image 2; meta data editing page
![image](https://user-images.githubusercontent.com/101448516/223136516-2388fc92-cafe-4f20-95a6-f0d687394972.png)
Image 3: data table without the licence updated
![image](https://user-images.githubusercontent.com/101448516/223136718-371b1410-799a-4080-9d88-9b9a7ce95c03.png)

### Bug Reproduction

Visit the Data page and you will see the aforementioned datasets.Click on the edit Meta data

### Bug Impact

Licence information doesnot get updated

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by JinIgarashi** [comment]
it is solved now
