### ISSUE TITLE
[FEATURE] Link directed to the simulation tab for Dynamic Subnational HDI

### ISSUE THREAD

**Issue by s6sapolw** [UNDP-Data/geohub#1497]
### Feature Description

In order to share the URL within the Data Futures Page, it would be nice to have a direct link to the simulation tab of Dynamic Subnational HDI. This will help users to view this key feature immediately. 
![image](https://user-images.githubusercontent.com/101448516/223459508-8a4c50e9-d805-40f8-aad7-90e88672c199.png)

### Feature Impact

It enhances the key features offered by the GeoHub

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201770671) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
In order to implement this, I think we can store active tab information in Layer object in $layerList. so it will be saved in database
