### ISSUE TITLE
[BUG] in Dynamic Maps, the slider's cursor keeps bouncing until the maps are loaded

### ISSUE THREAD

**Issue by rafdouglas** [UNDP-Data/geohub#1503]
### Bug Description

in Dynamic Maps (HDI), the slider's cursor keeps bouncing until the maps are loaded

### Bug Reproduction

1. Add the "Dynamic Subnational Hdi" layer
2. Click on a card
3. Move the slider.

The dot-shaped cursor on the slider will bounce left and right (and the shown values change accordingly) several times until the map is fully loaded.

If the layer is used, even after selecting a card but with the slider set to "0", this issue does not show up.

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by Thuhaa** [comment]
Closeing as it has been fixed by #1513
