### ISSUE TITLE
[BUG]  vector layers "Legend" tab -> "Classify" -> change property does not yield any effect

### ISSUE THREAD

**Issue by rafdouglas** [UNDP-Data/geohub#1514]
### Bug Description

For vector layers (tables/functions/views), under the "Legend" tab ->  "Classify" -> change property does not yield any effect on the map's style

If a different color ramp / style / Number of Classes are selected with the default property (=attribute), it works, and changes are reflected on the map.
However, if the "Property" is changed to another attribute, the color swatch on the layer card changes, but the map remains the same.

As a comparison/hint, changing the Property on the Label tab works

### Bug Reproduction

Add the "Dynamic Subnational Hdi" layer

 "Legend" tab ->  "Classify" 
it will show up with the HDI Property as default

change  "Property" to "Z" (all features should now have the same value), and change the color ramp, it does not change the map

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by JinIgarashi** [comment]
@rafdouglas I fixed error of maplibre in this PR #1530, but there is a problem of data type from pg_tileserv. check my comment on PR.
