### ISSUE TITLE
[BUG] - some "view" layers cannot classify features in order to color them 

### ISSUE THREAD

**Issue by rafdouglas** [UNDP-Data/geohub#1538]
### Bug Description

for some view layer, the coloring by classification gives an error.
This probably happens for layers/views in which all features have exactly the same value, and the endpoint cannot calculate the min/max dynamic.

### Bug Reproduction

filter by SDG -> 10.6

add the "Proportion Of Members Of Developing Countries In International Organizations, By..." layer 

activate the debug console in the browser

select Legend -> Classify -> Select "value_latest" from the Properties menu

**Comment by rafdouglas** [comment]
![image](https://user-images.githubusercontent.com/18248460/224764950-ee5aee4c-0443-4ae6-95d3-d2f982e2de06.png)

**Comment by JinIgarashi** [comment]
https://dev.undpgeohub.org/?operator=and&limit=15&style=194&staronly=true&queryoperator=and&sortby=name%2Casc
