### ISSUE TITLE
[BUG] - opening a saved maps does not show the saved layers

### ISSUE THREAD

**Issue by rafdouglas** [UNDP-Data/geohub#1540]
### Bug Description

Loading a saved map shows the map itself, but the layer is not loaded in the layer list.
Also, clicking on a represented feature does not show the pop-up info box

![image](https://user-images.githubusercontent.com/18248460/224762369-b5bfd06e-fa2e-4bef-b6da-085f24679922.png)

### Bug Reproduction

https://dev.undpgeohub.org/?style=196

**Comment by JinIgarashi** [comment]
I found it does not work since this commit.
https://github.com/UNDP-Data/geohub/commit/9b87d8e6d24f58ee1a00540ab5feac417c72e1c6#diff-2debaee1053cfd0ad577323527a22570a4d3e2fc2d596557f4a4a3e35b0a4df8
