### ISSUE TITLE
[BUG] vectori layers - streaming legend name

### ISSUE THREAD

**Issue by rafdouglas** [UNDP-Data/geohub#1544]
### Bug Description

Selecting vector layers (at least those served by pg_tileserv) initially shows a list of correct names (like "Dynamic Subnational HDI"), which then gets changed into the format:
schema.table_name
or
schema.view_name
or
schema.function_name

Looking at the progression of entries being renamed, it could be tied to the streaming paradigm.

### Bug Reproduction

![image](https://user-images.githubusercontent.com/18248460/224835472-e1bf742c-37a8-4a83-9a83-a217fdc54d57.png)

**Comment by JinIgarashi** [comment]
@rafdouglas I cannot reproduce this. Could you write precise reproduction steps?
