### ISSUE TITLE
[BUG] Simulation tab should not be shown in pgtileserv static layer

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#1558]
### Bug Description

nothing is shown in simulation tab. the tab should not be shown

### Bug Reproduction

https://dev.undpgeohub.org/?style=199

### Bug Screenshots

<img width="905" alt="image" src="https://user-images.githubusercontent.com/2639701/225419122-d5f415bc-ebf1-41db-952b-5eb432482b11.png">

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by rafdouglas** [comment]
If a function layer exposes an empty `params→values`, or has no `params→values`, then the `simulation` tab should not be displayed.

Linked with [https://github.com/UNDP-Data/geohub/discussions/1568](https://github.com/UNDP-Data/geohub/discussions/1568)
