### ISSUE TITLE
[BUG] datasets URL which contains ","  url is changed to %2C by encoding and has issue

### ISSUE THREAD

**Issue by s6sapolw** [UNDP-Data/geohub#1607]
### Bug Description

Issues with data sets with "," in the URL for meta data update.

### Bug Reproduction

https://dev.undpgeohub.org/data/publish?url=https://undpngddlsgeohubdev01.blob.core.windows.net/responsible-consumption-and-production/Global_Pesticide_Grids/Quality_Index/QI_Corn_2%2C4-d.tif
There are 77 data sets with similar issue

### Bug Impact

Difficult to update data and user readability .

### Bug Screenshots

![image](https://user-images.githubusercontent.com/101448516/226665979-4fbd0773-a7b8-4b62-9879-0d88eb1d3bdb.png)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by JinIgarashi** [comment]
I fixed the data by the following SQLs. migrated tags and metadata to the correct IDs

```sql
# migrate datasets to the correct ID
INSERT INTO geohub.dataset(id, url, is_raster, license, bounds, createdat, updatedat, name, description, created_user, updated_user)
SELECT MD5(replace(url, '%2C',',')) as id, replace(url, '%2C',',') as url, is_raster, license, bounds, createdat, updatedat, name, description, created_user, updated_user
	FROM geohub.dataset
	where url like'%\%2C%'
	ON CONFLICT DO NOTHING

# migrate tags to new datasets IDs
with replaceId as (
SELECT id as oldid, MD5(replace(url, '%2C',',')) as newid FROM geohub.dataset
	where url like'%\%2C%'
)
INSERT INTO geohub.dataset_tag (dataset_id, tag_id)
select b.newid, a.tag_id from geohub.dataset_tag a
inner join replaceId b
on a.dataset_id = b.oldid
ON CONFLICT DO NOTHING

# delete old IDs
delete from geohub.dataset where url like'%\%2C%'
```

The following CSVs are the result of datasets and tags which I migrated
[datasets.csv](https://github.com/UNDP-Data/geohub/files/11030866/datasets.csv)

[dataset_tag.csv](https://github.com/UNDP-Data/geohub/files/11030867/dataset_tag.csv)

**Comment by s6sapolw** [comment]
The bug is resolved and datasets can be published.
