### ISSUE TITLE
[FEATURE] add join vector tiles in one layer option to data upload

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#1923]
### Feature Description
When users upload data vector layers can be pushed to a multi-layer pmtiles file. A checkbox (unchecked) would indicate the user wants to have one pmtiles as opposed to each vector layer  into its own layer

### Feature Implementation

* [x] #1925
* [x] #1924

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214705519) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
new message format is defined in discussion page

https://github.com/UNDP-Data/geohub/discussions/545#discussioncomment-7121294
