### ISSUE TITLE
[BUG] payload too large errror on udating a saved map

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#1949]
### Bug Description

updating and saving a map 

failed with an error

### Bug Reproduction

https://dev.undpgeohub.org/map/243?queryoperator=and&sortby=name%2Casc#9.83/40.7068/-73.9359

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1221512050) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
Looks like we need to set `BODY_SIZE_LIMIT` environmental variables for adapter-node

References:
- https://kit.svelte.dev/docs/adapter-node#environment-variables-bodysizelimit
- https://www.reddit.com/r/sveltejs/comments/z3jb75/how_to_post_a_form_request_with_a_large_file/

**Comment by JinIgarashi** [comment]
This is where sveltekit adapter-node is setting default value

https://github.com/sveltejs/kit/blob/715dfdd2236111d475ba451046ac8c4e272a937f/packages/adapter-node/src/handler.js#L21

**Comment by JinIgarashi** [comment]
I added `BODY_SIZE_LIMIT` variable in AppService as `5242880` = 5MB. Let's see
