### ISSUE TITLE
[BUG] Put more margin in supported format page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2061]
### Bug Description

Put more margin in supported format page

### Bug Reproduction

<img width="557" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/d25c87a2-eaa6-4bf8-bd4b-30efdf8bde21">

<img width="1085" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/8958746d-eaed-4aee-8b43-e4155c6d5bcb">

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234871614) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
One more thing, put more space between extensions.

Maybe you can use bulma tag for extension (https://bulma.io/documentation/elements/tag/)

<img width="881" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/494f8a96-2b63-4bb6-a98a-617e7c83d0e3">

**Comment by JinIgarashi** [comment]
@Thuhaa 

You still need to put more margin. It is too narrow space between the edge of header and the title

<img width="1503" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/c2da8ebd-89d0-4588-ae2c-55f0e9c39808">

**Comment by Thuhaa** [comment]
Closig as it has been solved by #2078
