### ISSUE TITLE
[FEATURE] Improvements of data upload page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2062]
### Feature Description

I have some suggestions to improve data upload page layout.

- put elements in this order
  - dropzone
  - upload button (make it much bigger, use `is-large` of bulma)
  - checkbox for Every layer (Point, Line, Polygon) into into its own file
  - selected file list
  - citation link for supported page
- make Name of archive control hidden (I don't think this is helpful for users and they will edit).
- select files to upload button should be smaller than current one. the balance of drop zone and button are not good

 

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234875551) by [Unito](https://www.unito.io)

**Comment by Thuhaa** [comment]
@JinIgarashi This is going to be closed by #2072. Only issue not handled is hiding of TextInput component
