### ISSUE TITLE
[BUG] Error notification is not shown when just a single file is dropped in zone

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2063]
### Bug Description

Error notification is not shown when just a single file is dropped in zone

### Bug Reproduction

drop an any non geospatial file 

<img width="1085" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/959afb55-ba91-449b-a192-b76100b0038c">

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234880112) by [Unito](https://www.unito.io)

**Comment by Thuhaa** [comment]
Closing as it was fixed by #2088
