### ISSUE TITLE
[FEATURE] level 2 satellite imagery functionality in STAC explorer

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2159]
### Feature Description
This feature is part of satellite imagery capabilities in GeoHub. The goals of this  feature is to enable users to create satellite imagery products (indices) in an easy way. Concretely, the STAC explorer will be enhanced and allow users to select  predefined indices from a drop-down  menu below the asset selector.

The list for indicators will be curated and is satellite/instrument specific. However, some indices(NDVI) will be available in multiple satellites.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241301378) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
https://pro.arcgis.com/en/pro-app/latest/help/data/imagery/indices-gallery.htm
