### ISSUE TITLE
[BUG] wrap the tabs for legend panel in case the tabs do not fit inside nicely 

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2258]
### Bug Description

when there are more than 3 tabs in legend panel they exceed the width of the panel and a scroll bar is visible. This ruins a bit the UX and needs to be taken care of

### Bug Reproduction

add dynamic vector layer

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1249710545) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
This code works in my local

![image](https://github.com/UNDP-Data/geohub/assets/2639701/f0f12bfa-a13a-40b8-8a19-3c262940229b)

![image (1)](https://github.com/UNDP-Data/geohub/assets/2639701/39d4db06-2e9d-4122-8adc-33eeda36933e)

<img width="419" alt="image (2)" src="https://github.com/UNDP-Data/geohub/assets/2639701/9f446c61-2992-482e-88c6-0da338db1fb1">

**Comment by Thuhaa** [comment]
Closing as it has been fixed by #2267
