### ISSUE TITLE
[BUG] Last class has no value in vector layer

### ISSUE THREAD

**Issue by Thuhaa** [UNDP-Data/geohub#2272]
### Bug Description

In vector layers, the last class has no displayed end value
![image](https://github.com/UNDP-Data/geohub/assets/45137948/d1d82a32-b440-4289-9654-6a5a593962a3)

### Bug Reproduction

1. Load `Dynamic Subnational Hdi` layer
2. Make sure that the `hdi` attribute is selected

### Bug System Information

- OS: Ubuntu 22.04
- Browser: Google Chrome

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1250099033) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
@Thuhaa this is not bug. I changed function to expression for classifying. The last value is default value which doesn’t have specific value.
I think we can put some label like ‘others’ there

**Comment by JinIgarashi** [comment]
Also we should remove column of start value from table.

**Comment by Thuhaa** [comment]
> @Thuhaa this is not bug. I changed function to expression for classifying. The last value is default value which doesn’t have specific value. I think we can put some label like ‘others’ there

Noted. Will adjust issue accordingly
