### ISSUE TITLE
[BUG]  unexpected CORS error on loading/opening map with cached layers

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2274]
### Bug Description

when opening/restoring layers from cache the GeoHub map is encountering CORS errors

### Bug Reproduction

click on map

### Bug Screenshots

![image](https://github.com/UNDP-Data/geohub/assets/92793531/dd12b637-103a-4842-a021-15b5d601a18c)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1250173983) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
let me close it
