### ISSUE TITLE
[FEATURE] optimise icon size of breadcrumbs

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2308]
### Feature Description

Some icons on breadcrumbs are larger than text

<img width="612" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/8e7e30a8-c32e-4e06-a0b3-d0ab59a26af2">

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252828971) by [Unito](https://www.unito.io)

**Comment by Thuhaa** [comment]
Closing as it has been fixed by #2318
