### ISSUE TITLE
[BUG] the style of clickable breadcrumbs is not working

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2309]
### Bug Description

In original UNDP breadcrumbs, clickable breadcrumbs should be red color and show pointer cursor when it is hovered.

Currently, clickable ones have no difference from the last one.

https://design.undp.org/?path=/story/components-navigation-components-breadcrumbs--breadcrumbs

### Bug Reproduction

<img width="612" alt="image" src="https://github.com/UNDP-Data/geohub/assets/2639701/cb7b5ef8-e0d4-4345-97ca-44b1dffc963d">

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252829497) by [Unito](https://www.unito.io)

**Comment by Thuhaa** [comment]
Closing as it has been fixed by #2318

**Comment by Thuhaa** [comment]
closing as it has been fixed by #2318
