### ISSUE TITLE
[FEATURE] Map view to search datasets in data page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2368]
### Feature Description

It would be nice to have a map view in data page to explore datasets.

But currently, most of datasets are global ones, these global datasets should be excluded in map view

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1259122311) by [Unito](https://www.unito.io)

**Comment by iferencik** [comment]
Most of GeoHub datasets are global at this point and as such it makes little sense to create a map view. However this would make much more sens in future once users from country offices start to upload  country level data
