### ISSUE TITLE
[DATA] aggregate HREA to 2 km resolution so it can be used in el access dashboard

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2464]
### Issue Description

HREA data is sparse and it can not be compared easily with ML el access data. Alternatively custom pyramids might be a better solution

### References

https://geohub.data.undp.org/data?queryoperator=and&operator=and&sortby=updatedat%2Cdesc&limit=10&offset=10&query=electricity+access+estimate

### Dataset ID

https://geohub.data.undp.org/data/724417aac902cc839818fcca21548b2e

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265125353) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
this was already fixed
