### ISSUE TITLE
[BUG] Prevent switching of map to continous when user moves rescale while in interval legend

### ISSUE THREAD

**Issue by Thuhaa** [UNDP-Data/geohub#2525]
### Bug Description

1. When you load a raster layer and switch to classified legend, if the rescale is not set to min and max values and you use the slider to rescale in min, max, the map seems to change to continous

### Bug Reproduction

1. Load this layer `Min Temperature May`
2. Switch to interval/classfied legend
3. Open the controls for rescale and move the slider
4. You will notice that the map is converted to continous colormap

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1270569380) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
https://github.com/UNDP-Data/geohub/blob/fc761bd8074113b62a10ae800a1e195a14041b7d/sites/geohub/src/components/maplibre/raster/RasterLegend.svelte#L96-L113

I guess this code makes bug. need to check whether layer is simple or claccify legend

**Comment by JinIgarashi** [comment]
https://github.com/UNDP-Data/geohub/blob/fc761bd8074113b62a10ae800a1e195a14041b7d/sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte#L246-L252

also this code has issue for the bug, I think
