### ISSUE TITLE
Adjust style in the map sidebar elements

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#2608]
### Feature Description

1) Tab text elements fonr-size should be 1rem/16px 
<img width="1199" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/352fac5a-be71-47ae-a96f-f5fee30c3d0d">

2) padding left and right for these icons should be 0.75rem
<img width="374" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/5074ca19-830d-4ca5-890e-bc20f9bfe931">

3) For the layer icons, please make sure that spacing between two icons equals to 0.75rem/12px (px-2 and ml-1 classes would work)
<img width="246" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/a25e7638-89f5-40d3-bd24-c6c5065b081b">

4) border-bottom for accordion items (for all accordions in the geohub) should be #D4D6D8 (gray-400)
<img width="868" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/686fbbbd-f0e1-4ef6-8f44-b45e796adb8b">

5) Accordion chevrons look different in the left and right sidebar. In the left one, they are smaller and look more balanced, so let's use these chevrons for all accordions
<img width="1399" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/784b802f-6bbf-4514-aade-eb18d4718374">

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1274656632) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
No.5 is not yet fixed
