### ISSUE TITLE
[BUG] saved map fails to open

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2831]
### Bug Description

Saved map https://geohub.data.undp.org/maps/296/edit#4.18/17.22/9.73

fails to open

### Bug Reproduction

find the map and try to open uisng open button
![image](https://github.com/UNDP-Data/geohub/assets/92793531/e930569e-f539-4bdd-94da-b9d8ce32ed49)

### Bug Screenshots

![image](https://github.com/UNDP-Data/geohub/assets/92793531/591524a7-d5c2-4aca-81ed-46454adf4e7e)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1297544812) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
It was caused by deleting the dataset used in saved style. we need to add error handling when a dataset in saved style is deleted. we can delete dataset from the response of `/style/{id}` api
