### ISSUE TITLE
[BUG] set map access level to lowest contained dataset access level

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2832]
### Bug Description

style https://geohub.data.undp.org/maps/288 contains CEEI layer with org access level.

This map should not be visible to unauthneticated users

### Bug Reproduction

log out of geohub and open https://geohub.data.undp.org/maps/288

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1297637372) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
regading this bug, what do you think removing inaccesible layer from saved map if user does not have enough permission? so user still can see other layers which they have permission to access
