### ISSUE TITLE
[UI/UX] Home Page Cards

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#2890]
### Description
Hey!  I noticed that the cards on the home page do not align with [the UNDP design system cards](https://design.undp.org/?path=/story/components-ui-components-cards-featured-card--featured-card). Let's make small changes to improve the look and feel of the first screen.

**Cards**

1) No border-radius (right now it is 0.75)
![](https://github.com/UNDP-Data/geohub/assets/73748770/19b19e2f-e4df-4174-8015-b19741d65d3e)

2) No shadow (see above)

3) No top-border for this type of cards. There are [cards](https://design.undp.org/?path=/story/components-ui-components-cards-content-card-without-image-without-emphasize--without-emphasize) with a tag that have a border, but we do not have a tag, so I would go with [the standard UNDP featured cards](https://design.undp.org/?path=/story/components-ui-components-cards-featured-card--featured-card).

4) Paddings should be 1.5rem (all sides) and 0.5rem between the title and text:
![](https://github.com/UNDP-Data/geohub/assets/73748770/48f6f523-c632-469f-b92e-5903588058c5)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303824909) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
@balagurova  Current svelte component version's card uses `Content Card`.

https://design.undp.org/?path=/story/components-ui-components-cards-content-card-without-image-without-emphasize--without-emphasize

But your linked URL is for Feature Card. Is it better to use Feature Card on home page instead of Content Card?
