### ISSUE TITLE
[UI/UX] Segmented Buttons

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#2905]
### Description

Let's align all segmented buttons to other input elements:
<img width="1078" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/c69a52f8-cca0-461f-a870-8137c4ccb7a3">

Suggesting to add: 
min-width: 108px;
height: 40px;
padding-left: 1.5rem;
padding-right: 1.5rem;
border: 1px solid #000;

regarding the height, let's align to this dropdown element:
<img width="348" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/7fa9910c-08e7-4174-8240-44e65ab05509">

Also, it would be nice to keep two options: with and without icons for the flexibility.

<img width="669" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/0593cf82-6a6a-4e67-9632-26df914c4bba">

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304643109) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
I think I can create a segment button component with this design
