### ISSUE TITLE
[UI/UX] - Electricity Dashboard

### ISSUE THREAD

**Issue by jkmirano** [UNDP-Data/geohub#3131]
### Description
Electricity Dashboard new UI/UX design implementation and improvements:

* [ ] New Intro for Sidebar
* [ ] Accordion for Explore the evolution of electricity access at administrative level.
* [ ] Accordion for Compare empirical with maschine learning data.
* [ ] Accordion for Analyse bivariate data for wealth and access to electricity.
* [ ] Move time slider on the map when Explore accordion is clicked.
* [ ] Add Analyse bivariate legend
* [ ] Download button

### Screenshots
![](https://github.com/UNDP-Data/geohub/assets/57218353/cb0b874c-b545-4d7d-8651-4df942435aa6)
![](https://github.com/UNDP-Data/geohub/assets/57218353/708e8500-7b1e-4176-9722-663f9a2281f7)
![](https://github.com/UNDP-Data/geohub/assets/57218353/2d2c9cbc-e610-48a2-9029-a61da73ebda2)
![](https://github.com/UNDP-Data/geohub/assets/57218353/04f7c269-bdd2-4ede-aec0-eee624cae630)
![](https://github.com/UNDP-Data/geohub/assets/57218353/7e7bdf83-6c72-4498-835d-6cf58d33c224)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1325037201) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
AppService URL for develop-ibm branch is here: https://geohub-ibm.azurewebsites.net
