### ISSUE TITLE
add an extra text box for transform dialog input value below the slider so user can input a sepcific desired value directly

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#3343]
### Feature Description

![image](https://github.com/UNDP-Data/geohub/assets/92793531/ffe37539-5a20-4069-97b8-d0ff4b338326)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1343048069) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
There is NumberInput component which has capability for users to input manually in svelte-undp-components.

https://svelte-components.undpgeohub.org/?path=/docs/components-numberinput--docs

I think we should have a slider component with textbox in this package. This is not only a problem of raster transform. It is also problem for vector filter and raster algorithm.

We also have slider control for PropertyEditor component.

https://svelte-components.undpgeohub.org/?path=/docs/components-propertyeditor--docs#integer%20slider
