### ISSUE TITLE
the round indicator showing the selected basemap/style is out of sync with the real selected value

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#3528]
### Bug Description

when chaging the basemap the selected stykle is not the onw shown by round indicator as can be seen in picture

### Bug Reproduction

change base map

### Bug Screenshots

![image](https://github.com/UNDP-Data/geohub/assets/92793531/c1dc6c17-6be2-4661-b7ef-1e5e7199b9e2)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1369826368) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
@iferencik this is not a bug. The rounded button shows the next style image. Instead of selecting a style from popup, users can switch style to the next one by clicking rounded button.

**Comment by iferencik** [comment]
I understand and I like it. But i alos believe wen need to have a tooltip saying : Switch to next because it is not clear at all this is happening.
Alternatively trhe round button could be animated somehow giving the user the feeling he is switching to next

**Comment by JinIgarashi** [comment]
showing tooltip is a good idea.
