### ISSUE TITLE
static image API does not render map layers

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#3534]
### Bug Description

When rendering [map 308](https://geohub.data.undp.org/api/style/308.json) using staticimage API 

[https://staticimage.undpgeohub.org/playground?url=https://geohub.data.undp.org/api/style/308.json](https://staticimage.undpgeohub.org/playground?url=https://geohub.data.undp.org/api/style/308.json)

the result is incorrect, 

![image](https://github.com/UNDP-Data/geohub/assets/92793531/4ea84b18-2d90-436d-af11-76f9b478e26c)

thsi is how the map looks and a call to renderer

[https://staticimage.undpgeohub.org/api/style/static/-76.9837035596023,-12.043901743709569,11.278900320234508,0,0/300x200.webp?url=https%3A%2F%2Fgeohub.data.undp.org%2Fapi%2Fstyle%2F308.json&ratio=1](https://staticimage.undpgeohub.org/api/style/static/-76.9837035596023,-12.043901743709569,11.278900320234508,0,0/300x200.webp?url=https%3A%2F%2Fgeohub.data.undp.org%2Fapi%2Fstyle%2F308.json&ratio=1)

yields

![image](https://github.com/UNDP-Data/geohub/assets/92793531/00fa9254-f552-4c5b-a278-3e920bbfa132)

### Bug Reproduction

export map using static image API

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1370843176) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
I found symbol layer is not rendered

- Narok meter data

https://geohub.data.undp.org/maps/319#Preview

https://staticimage.undpgeohub.org/api/style/static/35.86614300263955,-1.0861562650539867,10.637302528000921,0,0/300x200.webp?url=https%3A%2F%2Fgeohub.data.undp.org%2Fapi%2Fstyle%2F319.json&ratio=1

- Oferta point data

https://geohub.data.undp.org/maps/318

http://localhost:5173/api/style/static/-77.06092096196676,-12.07848805527216,11.612919839356195,0,0/300x200.webp?url=https://dev.undpgeohub.org/api/style/318.json&ratio=1

**Comment by JinIgarashi** [comment]
The below is the layer which has trouble. When I manually call map.addLayer to add this layer, I got the error of TypeError: layer doesn't support this property. I found the layer spec works after removing icon-overlap property. 

```json
{
   "id":"384a6329-4847-4ce1-84aa-b77c13cf3daf",
   "type":"symbol",
   "source":"196af310ffb45117cb4f091fa5d98705",
   "source-layer":"meter",
   "minzoom":0,
   "layout":{
      "icon-image":"water",
      "icon-size":2.75,
      "icon-overlap":"always",
      "text-variable-anchor":[
         "top",
         "bottom",
         "left",
         "right"
      ],
      "text-radial-offset":0.5,
      "text-justify":"auto",
      "text-font":[
         "Proxima Nova Regular"
      ],
      "text-field":[
         "get",
         "customer"
      ],
      "text-size":12,
      "text-max-width":10,
      "visibility":"visible"
   },
   "paint":{
      "icon-color":"rgb(1,128,254)",
      "icon-opacity":1,
      "icon-halo-color":"rgb(255,255,255)",
      "icon-halo-width":1,
      "text-opacity":1,
      "text-halo-width":1,
      "text-color":"rgb(0,0,0)"
   }
}
```

**Comment by JinIgarashi** [comment]
it is not yet solved
