### ISSUE TITLE
failed to change permission of dynamic layer 

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#3537]
### Bug Description
I tried to change permission to UNDP for 

https://geohub.data.undp.org/data/320cf4ffcf6414a68b428f14a5728053

but i can't see anything

### Bug Reproduction
access the  dataset

### Bug System Information

* OS: [e.g. Windows 10]
* Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1371013314) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
![image](https://github.com/UNDP-Data/geohub/assets/2639701/b86e0a61-b587-4e25-805b-5c616d909ab2)

Because created_user is `geohub-cli`, it failed to get domain name when you changed access level to organization.

I updated created_user and updated_user to `data@undp.org`

```sql
Update geohub.dataset
set created_user='data@undp.org'
where created_user='geohub-cli'

Update geohub.dataset
set created_user='data@undp.org'
where created_user='geohub-cli'
```

**Comment by JinIgarashi** [comment]
@iferencik I also changed access level back to public for dynamic HDI dataset. I don't think there is a problem of making access level as organization for this dataset. there are multiple maps using this dataset layer, it is not good to change access level like this.
