### ISSUE TITLE
URGENT: vector labels not working

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#3547]
### Bug Description

Currently not possible to label vector layers

![image](https://github.com/UNDP-Data/geohub/assets/92793531/0dea26ed-c2a4-4472-b777-4510acd996b4)

### Bug Reproduction

layer properties label

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1371978417) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
@iferencik could you explain precisely how to reproduce? It looks working well in my browser

![image](https://github.com/UNDP-Data/geohub/assets/2639701/8c843c6f-9436-4e10-b485-802cf4580d8d)

**Comment by JinIgarashi** [comment]
let me close the issue. feel free to reopen if it is still there

**Comment by JinIgarashi** [comment]
I can now reproduce in incognito window of safari
