### ISSUE TITLE
[BUG] delete microsoft planetary from stac

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3615]
### Bug Description

microsoft pc's sentinel seems registered for product. you should delete it since it does not work.

### Bug Reproduction

https://dev.undpgeohub.org/api/stac/microsoft-pc/sentinel-2-l2a/products

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by Thuhaa** [comment]
Deleted Microsoft PC from products
