### ISSUE TITLE
[BUG] Reset all local storage when users leave map edit page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3695]
### Bug Description

As @iferencik mentioned, keeping previously opened existing map in local storage is confusing when users add new data from /data page.

The following things need to be changed to improve.

- Delete all local storage when users are leaving map edit page
- Reset all local storage when users add new data from /data page

### Bug Reproduction

currently, previously opened maps are remained in local storage.

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by iferencik** [comment]
> ### Bug Description
> As @iferencik mentioned, keeping previously opened existing map in local storage is confusing when users add new data from /data page.
> 
> The following things need to be changed to improve.
> 
> * Delete all local storage when users are leaving map edit page

the above I am not sure you need to remove it. to be honest

> * Reset all local storage when users add new data from /data page
> 
> ### Bug Reproduction
> currently, previously opened maps are remained in local storage.
> 
> ### Bug Impact
> _No response_
> 
> ### Bug Screenshots
> _No response_
> 
> ### Bug References
> _No response_
> 
> ### Bug System Information
> * OS: [e.g. Windows 10]
> * Browser: [e.g. Google Chrome, Firefox]
