### ISSUE TITLE
Replace zonal stats for new datasets

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3785]
- generate new zonal stats admin data

follow steps of ` Generate admin level zonal stats` at https://github.com/UNDP-Data/geo-cellular-automata/blob/main/hreaibm.md

- register new PMTiles to GeoHub

Upload PMTiles to hrea container of blobstorage

- Replace admin data at the below code

https://github.com/UNDP-Data/geohub/blob/743d8716107ec82b6f3e03e9cf172f65f817bfb7/sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts#L128-L151

Currently using static pbf tiles. we might need to change quite a lot of codes by switching static pbf to PMTiles. also need to check if there is any changes on column names.

- line chart

In the line chart component, some code uses data from admin. maybe this code needs to be modified.

https://github.com/UNDP-Data/geohub/blob/b3edab4cc0f9b5c91a5fee201b4b39bb455f1648/sites/geohub/src/routes/(map)/dashboards/electricity/components/Charts.svelte#L146-L180

**Comment by JinIgarashi** [comment]
Let me update what we ended up with zonal stats work since you left. Joseph was trying to generate zonal stats by using your approach described in github repository (https://github.com/UNDP-Data/geo-cellular-automata/blob/main/hreaibm.md).
 
This approach is trying to estimate electricity access rate by using the number of pixels which has more than 80% electricity access rate. The percentage is calculated from dividing the number of pixels with electricity by the total number of pixels. However, we discovered this approach does not give us better figures. 
We think population data each pixel level is needed to estimate better access rate. that is what old admin data did to calculate electricity access rate from population. But we don't have population data for forecast one (2021-2030). we need to find different method to estimate future population and the percentage of electrified.
 
In conclusion, it is not feasible to include new zonal stats by this week (even by end of next week). We can deploy new electricity dashboard tomorrow without new zonal stats (we keep existing zonal stats as it is). In the future, we will find time to create zonal stats for 2021-2030.
 
Additionally, I want to let you know there is a new population dataset managed by OCHA. It is different from world pop. It has global vector population data from 2020 to 2023. As you can see preview of the below URL, this data has hexagon polygons where there is settlement, and each polygon has the number of population. We maybe can intersect this population data with our 1km aggregated raster to calculate the population each pixel. 
For the population after 2024, we may use this data to estimate population growth each polygon (maybe using 2022 and 2023 data) for future population. Then create global population datasets from 2024 to 2030 to get electricity access rate.
 
https://data.humdata.org/dataset/kontur-population-dataset?

**Comment by JinIgarashi** [comment]
Proposed steps to regenerate zonal stats for forcast electricity access (2021-2030) are:

## 1. Compute population with/without electricity access from 2021 to 2023

[Kontur population data](https://data.humdata.org/dataset/kontur-population-dataset) is available from 2021 to 2023.

- population data
  - 2021 - 2023: download from kontur (https://data.humdata.org/dataset/kontur-population-dataset)
- forecast data
  - 2021: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2021_1km.tif
  - 2022: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2022_1km.tif
  - 2023: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2023_1km.tif

each year's population data has hexagon polygons. we computer the `no of population with electricity access`, `no of population without electricity access` for each polygon. and add to `pop_hrea_2021` and `pop_no_hrea_2021` to the population geopackage in 2021 (repeat same process until 2023).

## 2. Download current admin data from 0 to 4

Current admin data is stored at the following blob storage.

- https://undpngddlsgeohubdev01.blob.core.windows.net/admin/adm0_polygons.gpkg.zip
- https://undpngddlsgeohubdev01.blob.core.windows.net/admin/adm1_polygons.gpkg.zip
- https://undpngddlsgeohubdev01.blob.core.windows.net/admin/adm2_polygons.gpkg.zip
- https://undpngddlsgeohubdev01.blob.core.windows.net/admin/adm3_polygons.gpkg.zip
- https://undpngddlsgeohubdev01.blob.core.windows.net/admin/adm4_polygons.gpkg.zip

These geopackages store columns for zonal stats from 2012 to 2020 like below:
- pop_hrea_20XX
- pop_no_hrea_20XX
- hrea_20XX

To minimise our work, we reuse this existing admin data with stats as much as possible.

## 3. Merge 2021 - 2023 data to current admin data

In step 1, we added population data to kontur geopackage. Now we can use `exactextract` to compute electricity access rate for each admin polygon by using step 1 result.

exactextract is described at [hreaibm.md](https://github.com/UNDP-Data/geo-cellular-automata/blob/main/hreaibm.md).

after this step, `hrea_2021` to `hrea_2023`, `pop_hrea_2021` to `pop_hrea_2023` and `pop_no_hrea_2021` to `pop_no_hrea_2023` should be added to downloaded admin data (from 0 to 4)

## 4. creating zonal stats for future population (2024 - 2030)

There is no future population data from 2024. We need to do this by several steps:

### 4.1 estimate future population by using kontur population data

1. Compare 2022 and 2023 population data, to estimate population growth ratio for each hexagon polygon in geopackage. Add population growth column to geopackage.
2. Use this population growth to simply estimate future poplulation from 2024 to 2030 for each grid. (add columns of future population like `pop_2024` to `pop_2030` to geopackage.

### 4.2 Computer electricity access population from 2024 to 2030

Using the following forecast data by combining estimated population, compute `no of population with electricity access`, `no of population without electricity access` for each polygon.

- forecast data
  - 2024: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2024_1km.tif
  - 2025: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2025_1km.tif
  - 2026: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2026_1km.tif
  - 2027: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2027_1km.tif
  - 2028: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2028_1km.tif
  - 2029: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2029_1km.tif
  - 2030: https://undpgeohub.blob.core.windows.net/hrea/Electricity_access_forecast_2030_1km.tif

### 4.3 Merge 2024 - 2030 data to current admin data

do the same process of step 3 to merge 2024 to 2030 data to current admin data.

## 5. Convert gpkg to fgb by GDAL/OGR

to do from admin 0 to admin 4

## 6. Convert fgb to PMTiles by using tippecanoe

to do from admin 0 to admin 4

## 7. Upload `fgb`, `gpkg` and `pmtiles` to blob storage

to do from admin 0 to admin 4

we can upload all files to `https://undpgeohub.blob.core.windows.net/hrea` container.

## 8. Replace admin data to new one in sveltekit.

If all columns name follow existing admin data, we can minimize changes on frontend.

**Comment by JinIgarashi** [comment]
zonal stats for kontur population datasets (output of step 1 above) are:

- 2021: https://undpgeohub.blob.core.windows.net/hrea/exactextract/kontur_population_20211109_hrea.gpkg.zip
- 2022: https://undpgeohub.blob.core.windows.net/hrea/exactextract/kontur_population_20220630_hrea.gpkg.zip
- 2023: https://undpgeohub.blob.core.windows.net/hrea/exactextract/kontur_population_20231101_hrea.gpkg.zip

the below 2020 data is for comparison with existing 2020 data

- 2020: https://undpgeohub.blob.core.windows.net/hrea/exactextract/kontur_population_20200928_hrea.gpkg.zip

**Comment by JinIgarashi** [comment]
https://gis.stackexchange.com/questions/436463/weighted-average-values-of-overlapping-polygons-in-python

**Comment by JinIgarashi** [comment]
population forecast algorithm is in these papers. maybe one of them can be used

- Projecting 1 km-grid population distributions from 2020 to 2100 globally under shared socioeconomic pathways
  - https://www.nature.com/articles/s41597-022-01675-x

- Projecting a Gridded Population of the World Using Ratio Methods of Trend Extrapolation
  - https://www.researchgate.net/publication/227129930_Projecting_a_Gridded_Population_of_the_World_Using_Ratio_Methods_of_Trend_Extrapolation

**Comment by JinIgarashi** [comment]
Step 1 - 3 are fixed by #3850

**Comment by iferencik** [comment]
I have uploaded new tiles with identical structure at https://undpgeohub.blob.core.windows.net/hrea/admin/forecast.
Additionally the fgb files are also uploaded
