### ISSUE TITLE
[UI/UX] Storymap Setup

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#3834]
### Description

**UX**

- I suggest moving 'Title', 'Subtitle', 'Logo,' and 'Credits' settings to the slides area. Let's add both header and footer slides to the slide thumbnails and allow users to edit them in 'Slide Settings'. Currently, users only see content slides, which can be confusing since the editor view and the preview differ. Also, a user might want to edit map setting for the header slide. I remember we discussed this on the call, so let's introduce this change.
- I'd recommend removing the 'Template' and 'Map' settings from the setup to simplify the user journey. It's also risky to let users overwrite individual slide settings and potentially delete their previous work. Instead, when users create the storymap, the first slide can use a light template with the 'base map' as the default option. Users can change these settings later in the slide settings.
- Let's keep just 'Continue' button since we already have the cross in the upper corner. It will also remove the confusion with colors. 
- Let's add 'Desription' field so that the users can add overview of the storymap which we can then use in the Info page. Also, it can help to search for the relevant storymaps. Let's make this field optional. 

Simplified Setup:
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/32b8c225-ef53-4430-a0e0-cbe8a7390820">

**UI**

- Modal heading should be similar to H5 style
<img width="586" alt="image" src="https://github.com/user-attachments/assets/0864cfb8-8b2a-4163-a3fd-eb5b1087b553">

- Colors of the cross icon should be gray-100 for background and black for the cross:
<img width="309" alt="image" src="https://github.com/user-attachments/assets/674f4463-0c21-451f-8bce-9fc8cb21b43b">

- I've updated segmented button style to black color and without icons to better align with the design system and to reduce the noise:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/acd8d672-4f03-4d73-9c21-ba54be903d88">

### Screenshots

Current:
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/173340e6-1a31-4499-87c9-6f0eca330e37">

Suggested:
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/553a9976-fc92-47b9-98a2-261d9322ac03">

### Mockup URL/file

https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3328-4434

**Comment by JinIgarashi** [comment]
I agree to have header and footer on the slide side bar.
