### ISSUE TITLE
[UI/UX] Delete button style of undp-bulma

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3844]
### Description

cross icon should be a bit different. I'm mentioning it here:
https://github.com/UNDP-Data/geohub/issues/3834 (in the UI part)
 
and also you can check it here:
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3328-4434

need to change style of UNDP bulma for delete class

https://bulma.io/documentation/elements/delete/

### Screenshots

current

![image](https://github.com/user-attachments/assets/22b5c27a-7621-47cb-9f13-6f5a6053de59)

proposed

![image](https://github.com/user-attachments/assets/cb6a73ad-4595-4852-b161-14c4db11d0c4)

**Comment by balagurova** [comment]
Hi Jin, I've checked the modal style in the UNDP design system, and it has the following parameters:
padding: 4rem;

cross icon: 
width: 1rem;
height: 1rem;

span around the cross:
position: absolute;
right: 1rem;
top: 1rem;
width: 45px;
height: 45px;
