### ISSUE TITLE
[UI/UX] header/footer mini preview on sidebar can be differentiate from normal chapter preview

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3852]
### Description

SInce header/footer were moved into sidebar, I think we need to differentiate both header/footer and chapter preview. 

### Screenshots

![image](https://github.com/user-attachments/assets/ac9715b1-c15c-4c4b-ab84-b571d633e2b2)

**Comment by balagurova** [comment]
[Figma prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5209)
