### ISSUE TITLE
[UI/UX] add navigation such as breadcrumbs to storymap editor page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3867]
### Description

currently, there is no way to go back to previous page from editor unless editing URL manually. need some UI to navigate users.

### Screenshots

current

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/a6cc1e8e-fef5-4773-8dae-a92e09dae6a9">

**Comment by balagurova** [comment]
[Figma prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5209)
