### ISSUE TITLE
[UI/UX] redesign storymap portal page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3877]
### Description

Current version of storymap portal (`/storymaps` page) UI is a bit complicated especially for filtering/searching components, it requires new UI to redesign.

### Screenshots

Current version

![image](https://github.com/user-attachments/assets/9ab45136-eaf7-475d-b62f-cf95151cd61c)

### Mockup URL/file

figma

https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3282-1940&m=dev

**Comment by balagurova** [comment]
[Figma Prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3282-1940)

**Comment by JinIgarashi** [comment]
@balagurova I implemented your current figma design for storymap portal (https://dev.undpgeohub.org/storymaps). I think it looks good. feel free to reopen the issue if anything needs to be changed
