### ISSUE TITLE
[UI/UX] redesign Maps portal

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3878]
### Description

related to https://github.com/UNDP-Data/geohub/issues/3877, Maps portal (`/maps` page) needs the same unified UI to redesign the layout.

**Comment by balagurova** [comment]
[Figma Prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3282-1940)
