### ISSUE TITLE
[UI/UX] redesign Data portal

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3879]
### Description

related to https://github.com/UNDP-Data/geohub/issues/3877, Data portal (`/data` page) needs the same unified UI to redesign the layout.

**Comment by balagurova** [comment]
[Figma Prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3282-1940)

**Comment by JinIgarashi** [comment]
to redesign data portal, I have developed new two components

I tried to make them look like UNDP design

CountrySelector

https://svelte-components.undpgeohub.org/?path=/docs/components-countryselector--docs

SDGSelector

https://svelte-components.undpgeohub.org/?path=/docs/components-sdgselector--docs
