### ISSUE TITLE
[UI/UX] Duplicate storymap feature

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3880]
### Description

Currently, users cannot modify existing storymap unless they have edit permission.

In a storymap page, maybe `Duplicate` button is needed to copy existing storymap as signed user owned storymap.

- Click `Duplicate` button
- Copy the storymap to create new storymap with owner permission for signed user
- Open editor for duplicated storymap

Something similar to `fork` functionality of Github. Maybe we can have another table to manage which storymaps are copied  to this.

- table: `storymap_duplicate`
- columns: 
  - `original_id`
  - `duplicated_id`
  - `duplicatedat`
  - `duplicated_user`

Then, we can show how many storymaps are duplicated from original one.

### Screenshots

- current

![image](https://github.com/user-attachments/assets/33784c9e-464b-4c5e-b401-a2e816405a56)

**Comment by balagurova** [comment]
Questions to discuss: 
Why do we need to see how many storymaps are created from the original one?

[Figma Prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3328-1783)
