### ISSUE TITLE
[UI/UX] UI to create storymap directly from a GeoHub map

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3881]
### Description

Since a storymap is basically created from a GeoHub map, it would be nice if there is a button on Map page to directly create a storymap without visiting to storymap portal.

maybe something button like `Create storymap from this map`  can be in a map page somewhere. If users click the button, open storymap editor with selected geohub map style.

### Screenshots

- current map page

![image](https://github.com/user-attachments/assets/3c994f91-c3e9-4728-b919-2fa2612ac068)

**Comment by balagurova** [comment]
[Figma Prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3476-11477)

**Comment by balagurova** [comment]
Please check button styles:
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3476-11478&t=fL2IysZMyzwiHjL7-1
