### ISSUE TITLE
[UI/UX] storymaps link on GeoHub landing page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3883]
### Description

the below screenshot is what I added storymaps menu in header and footer.

but we need to think how we put storymaps link in landing page, header and footer.

### Screenshots

![GeoHub](https://github.com/user-attachments/assets/b72b445f-ddb7-45b5-8433-c5ae26eb5148)

**Comment by balagurova** [comment]
My suggestions regarding the storymap navigation flow is here: [Figma Prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3122-66)

We should have another issue to align the home page to the UNDP design system.
