### ISSUE TITLE
[UI/UX] Prepare the logos of major UN agencies readily available

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3887]
### Description

currently, users have to find logo image file and drop&drop to add it to storymap. We can have a set of logos for major UN agencies such as UN, UNDP, UNICEF, WFP, etc. so users just select a logo to include it.

### Screenshots

- currrent

![image](https://github.com/user-attachments/assets/e10cb099-22fc-4f2e-9e0b-26f994dcce8a)

- proposed

maybe it can have tabs - file or logos
if select logos tab, it shows prepared UN agencies (or other logos).

**Comment by balagurova** [comment]
[Figma prototype](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5492&t=Q7LpNeZ4X4JQNzXV-1)
