### ISSUE TITLE
[UI/UX] UI design of slide progress bar of storymap

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3888]
### Description

slide progress bar feature was added via https://github.com/UNDP-Data/geohub/pull/3886, UI might need to be improved

- UI of slide progress bar (color, size of handle, etc)
  - progress bar is using svelte-range-slider component, the styling option is available https://simeydotme.github.io/svelte-range-slider-pips/en/styling
- UI of slide progress bar setting

### Screenshots

current progress bar screenshots

- slide progress bar

![image](https://github.com/user-attachments/assets/6a6085f5-2b5b-4fe0-be0f-aa3af85a8f6a)

- slide progress bar setting

![image](https://github.com/user-attachments/assets/f837949a-0c40-47df-9f00-0177933c738e)

**Comment by balagurova** [comment]
[Storymap Viewer](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-13191&t=Q7LpNeZ4X4JQNzXV-1)
[Storymap Setup](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3480-5438&t=Q7LpNeZ4X4JQNzXV-1)
