### ISSUE TITLE
[UI/UX] UP/DOWN button on slide preview in sidebar to change slide order

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3890]
### Description

Currently slide order cannot be changed. Drag and drop feature to change order will be implemented by this issue (https://github.com/UNDP-Data/geohub/issues/3889). however, it would be nice to have buttons (UP/DOWN) to move a chapter.

### Screenshots

current

![image](https://github.com/user-attachments/assets/f20125f0-7058-4a06-8949-c81a96915371)

maybe addition two buttons (UP/DOWN) to change order

maybe following icons can be used

- UP: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:keyboard_arrow_up:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=up&icon.size=24&icon.color=%235f6368
- DOWN: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:keyboard_arrow_down:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=down&icon.size=24&icon.color=%235f6368

**Comment by JinIgarashi** [comment]
@balagurova I implemented this feature by #3896. PR was already merged, but I will update UI later.

- first chapter

![image](https://github.com/user-attachments/assets/328ec500-4685-4355-ba68-9770913fd58f)

- middle chapter

![image](https://github.com/user-attachments/assets/7d92624d-23df-4e8e-a92d-60ada19e0350)

- last chapter

![image](https://github.com/user-attachments/assets/d9f54617-6804-4ae3-8905-92d8f216f5a8)

**Comment by balagurova** [comment]
[Figma prototype for this issue](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5210&t=UONgKBfBOy96YQqK-1
)

**Comment by balagurova** [comment]
Please remove the buttons (as discussed on the call)

**Comment by JinIgarashi** [comment]
reverted by #3905
