### ISSUE TITLE
[UI/UX] Responsive design for storymap viewer

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3898]
### Description

We need slightly diffrent UI design for responsive. maybe fontsize, padding, card size needs to be adjusted.

### Screenshots

<img width="499" alt="image" src="https://github.com/user-attachments/assets/bb8ec608-da84-4134-802a-97e603fd1052">

**Comment by balagurova** [comment]
[Figma prototype with comments](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3318-6229)
