### ISSUE TITLE
[UI/UX] Access level control is a little bit hidden for storymap

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3923]
### Description

Currently, access level for storymap is done from settings button.

![image](https://github.com/user-attachments/assets/4d481f2e-7c9b-4a4d-ad46-76b7ba22369d)

But this setting is a little bit hidden, and access level should be more highlighted for users.

Should access level be shown after clicking save button?

Proposed user's work flow
- edit storymap
- click `Save` button
- show confirmation dialog to save, and select access level as well (default is private)
- if click `save` in dialog, continue saving and close dialog.
- if click `cancel` in dialog, close dialog without saving.

**Comment by balagurova** [comment]
Please find a mockup here:
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3612-4190&t=BEqbZPIYnSjKX5Mm-1

**Comment by balagurova** [comment]
let's make buttons consistent: 
here it is outlined and with shadow:
<img width="660" alt="image" src="https://github.com/user-attachments/assets/bc70c606-e33b-4355-b179-0c465afc4cd2">

here it is grey:
<img width="637" alt="image" src="https://github.com/user-attachments/assets/e81672ec-38c5-43d8-8a2e-c4446440ad16">

I recommend choosing one style for all cases. Either keep it outlined (but without the shadow) or align it with the grey design.
