### ISSUE TITLE
[UI/UX] Improve layer selection

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3928]
### Description

we need to improve layer visibility setting on enter

### Screenshots

- current

![image](https://github.com/user-attachments/assets/1d9be780-79ce-40fe-ba8b-ae4f39e94f2c)

- proposed

![image](https://github.com/user-attachments/assets/a11fc543-849a-4f71-a3bd-74a178caa457)

### Mockup URL/file

https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5209&t=hWupnfhunkFduOFq-0

**Comment by balagurova** [comment]
Looks good! Could you please add an 8px margin-right to the opacity element? This will create more space and make the button easier to click.
