### ISSUE TITLE
[UI/UX] UI improvement for ModalNotification 

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3929]
### Description

https://svelte-components.undpgeohub.org/?path=/docs/components-modalnotification--docs

### Screenshots

- current

![image](https://github.com/user-attachments/assets/f760f803-1ce8-4754-bcfa-f6884e8c18f6)

- proposed

![image](https://github.com/user-attachments/assets/6a89ce6c-0e53-44c7-9731-de5897ae1fcc)

### Mockup URL/file

https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5209&t=hWupnfhunkFduOFq-0

**Comment by balagurova** [comment]
It looks great. I did notice one thing about the white buttons with the grey outline—they have a shadow that isn't in line with the UNDP style guide. Let's remove the shadow from all such buttons.

**Comment by balagurova** [comment]
Please change the order so that 'Delete' button is the first one (left)
