### ISSUE TITLE
[UI/UX] Redesign the the full width option for cards

### ISSUE THREAD

**Issue by mustafasaifee42** [UNDP-Data/geohub#3940]
### Description

![image](https://github.com/user-attachments/assets/9b370c9e-dfd9-4b11-8ffb-b4116f0fb043)

Anastasia to provide the design adn solution for this

**Comment by JinIgarashi** [comment]
@balagurova I renamed property to Card Size and Alignment, and introduced your current UI (default/fullwidth segment buttons). Screenshot is in the PR.
If this is still the case, please feel free to reopen the issue.

**Comment by balagurova** [comment]
Looks great! Just a tiny typo to fix: 'And' should be lowercase here
<img width="417" alt="image" src="https://github.com/user-attachments/assets/a025ac41-8ee5-4528-b76d-0652822f73e6">
