### ISSUE TITLE
[UI/UX] make slide transition segment button normal size

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3944]
### Description

size is different from others

### Screenshots

![image](https://github.com/user-attachments/assets/2c51d76d-5cb7-4253-a33d-e8b8f1f2d49b)

**Comment by balagurova** [comment]
Hi! The size looks good, but the font-weight still differs from other components. For consistency, let's use 400—it’s more common and visually lighter. Thanks!

400: 
<img width="358" alt="image" src="https://github.com/user-attachments/assets/7171df96-2d06-4d34-b8f3-2d4074967216">

<img width="404" alt="image" src="https://github.com/user-attachments/assets/fb1a9313-43ee-41bf-8c69-e47609ed0b54">

<img width="467" alt="image" src="https://github.com/user-attachments/assets/fa1398ab-4cc9-4b90-a54b-df8f45f3433a">


600:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/238e1045-2250-4e2e-93a7-32716fb8af09">

<img width="422" alt="image" src="https://github.com/user-attachments/assets/55fcb10b-01e4-4028-8fd8-9ac8020f9063">
