### ISSUE TITLE
[UI/UX] Slider UI design

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3957]
### Description

I like you are exploring new UI, but is it possible if you can design new UI of slider based on the below `svelte-range-slider-pips` package?

I tried to customise CSS style for your suggested design, but my conclusion is not possible to do it because it is too different from the package we are using.

The below is the slider component's website for available CSS styling parameters

https://simeydotme.github.io/svelte-range-slider-pips/en/styling/#structure

### Screenshots

Your suggested design

![image](https://github.com/user-attachments/assets/9fa97a80-cfa7-4329-87a4-fa95d29e8819)

**Comment by balagurova** [comment]
Hi @JinIgarashi. Yes, sure, let's use the available component. I would maybe just change the color of a circle (and all related elements) from bulma light blue to [blue-300](https://design.undp.org/?path=/docs/foundation-colors--docs) from the design system.

**Comment by balagurova** [comment]
Hi! Let's update the circle color (and all related elements like the hover label) from light blue to [blue-300](https://design.undp.org/?path=/docs/foundation-colors--docs) from the design system for consistency. Thanks!
