### ISSUE TITLE
[UI/UX] Edit legend in storymaps

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#3992]
### Description

Review and  provide mockup for different types of legend in the storymaps.
[Legend test map](https://dev.undpgeohub.org/maps/341)

**Comment by JinIgarashi** [comment]
I forgot to fix position of legend to bottom-left

**Comment by balagurova** [comment]
Hi @JinIgarashi 
I've updated the mockup for the legend, please have a look:
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3318-6229&t=b6TdoaYkWAEIAdZH-1

**Comment by balagurova** [comment]
@JinIgarashi Hi! Overall it looks much clearer and easier to handle, thanks for applying the changes! 

I've seen your comment in Figma regarding the collapsable items in the legend: 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/91e9d011-c263-4a30-824d-cbbe0df7322b">

I suggest removing the accordion feature from the legend since you've already implemented a max-height, which solves the same problem of keeping the legend box manageable. With the max-height, users can scroll through the legends without needing to collapse them. Having both features is redundant, and the accordion adds unnecessary noise and complexity. 

Please have a look at the suggested layout:
<img width="604" alt="image" src="https://github.com/user-attachments/assets/a272c3bf-c8b2-4a1e-bbe9-a07ea475c9bd">
_(in this example I just removed arrow icon and made padding-bottom 8px instead of 16px)_

**Comment by balagurova** [comment]
Looks great! Just one small thing: the rendered font for the title is Helvetica. Please change it to Proxima Nova. 
<img width="1667" alt="image" src="https://github.com/user-attachments/assets/6557c3fe-8afc-4e01-8c37-2f028f749305">
