### ISSUE TITLE
[UI/UX] Add a visual text editor in storymaps

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#4100]
### Description

Please explore the possibility to add a visual text editor to the storymaps editor in these two sections:

- 'Description' in the card settings. Please note that 'Title' and other text inputs should be just text inputs, without md or visual editor features. 
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/a12d151e-00a6-40e1-a4dc-f27b9330e818">

- 'Description' in a new footer tab

**Comment by JinIgarashi** [comment]
https://beartocode.github.io/carta/examples

**Comment by JinIgarashi** [comment]
I might not be able to do this. carta does not work with geohub (maybe because of bulma and undp design css affected, i guess)

**Comment by balagurova** [comment]
Great job on finding the editor! Just a quick note: I noticed that the font color in the neighboring text inputs is different. Could you please adjust the CSS of the visual editor so the input placeholders match the others?
<img width="514" alt="image" src="https://github.com/user-attachments/assets/f864b04c-9308-46ed-9b50-749e82ea0fe6">

**Comment by balagurova** [comment]
Sorry for reopening, I noticed that the borders are different. Are those easy to change? It would look visually more consistent. 

Current:
<img width="463" alt="image" src="https://github.com/user-attachments/assets/a2ec91c8-4348-4aaa-b429-c3ad1de36bac">

Updated (borders are black and border-radius is set to 0):
<img width="489" alt="image" src="https://github.com/user-attachments/assets/1a58d3b8-55fe-4105-b5e6-64193e9db4c7">
