### ISSUE TITLE
[UI/UX] Footer tab for the last slide of storymap editor

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#4102]
### Description

Add `Footer` tab in the last slide editor to show footer text box together with markdown editor.

**Comment by balagurova** [comment]
This is a mockup for the footer settings:
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3732-5474&t=7smyGEgydv4nXbsf-1 

<img width="351" alt="image" src="https://github.com/user-attachments/assets/05b4a6fe-0545-4376-9969-871b164fe452">
