### ISSUE TITLE
[UI/UX] Thumbnail content in storymaps editor

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#4109]
### Description

Let’s update the last slide thumbnail to include the footer block, so users can visually identify that they can edit the footer and that it will appear in the final chapter. 

I suggest adding a gray-200 block at the bottom with a height of 25%, then placing the footer text inside. You can limit the text to two or three lines, and if you'd like, there’s a CSS feature ('-webkit-line-clamp: 2;') that allows you to easily truncate the text after a specific number of lines. 

The goal isn’t for the text to be legible, but to visually represent the elements, making it easier to differentiate slides by preview.

<img width="606" alt="image" src="https://github.com/user-attachments/assets/6454b4da-2b2c-4487-998b-2b241010f396">

**Comment by JinIgarashi** [comment]
I don't think we need to add footer in sidebar preview. it will be too noisy and will interrupt users to see menu buttons.

**Comment by balagurova** [comment]
That's a good point. I think it's not just about the footer, but also when the map is too light, making the buttons hard to see. Check out the example below. Let's tackle this in a separate ticket. 

As for the footer, it's important to visually show that the last slide is different with an extra element. I suggest we add a simple rectangle without text (I agree, adding text makes it too busy). The rectangle specs: height 20px, background gray-200, no text inside. 

Low visibility of buttons:
<img width="321" alt="image" src="https://github.com/user-attachments/assets/410e85e5-6c6e-4648-b717-6c1cf8163569">
Rectangle: 
<img width="321" alt="image" src="https://github.com/user-attachments/assets/5a14db0a-b1fa-47a5-9d85-38f6348ef39d">

**Comment by JinIgarashi** [comment]
@balagurova I think adding a stripe for footer in the last slide is good idea. for the button menu visibility, maybe we can add box-shadow in the menu button?

**Comment by balagurova** [comment]
> @balagurova I think adding a stripe for footer in the last slide is good idea. for the button menu visibility, maybe we can add box-shadow in the menu button?

This is a good idea. Alternatively, we can add a border as in these elements on the maps. I will create a new issue for that today or tomorrow. 
<img width="370" alt="image" src="https://github.com/user-attachments/assets/41fc9a1b-0578-4a9f-a692-a654c97e6ae5">
