### ISSUE TITLE
[UI/UX] GeoHub Landing Page

### ISSUE THREAD

**Issue by balagurova** [UNDP-Data/geohub#4267]
### Description

Let's start redesigning the landing page

### Screenshots

As it is now:
![screencapture-geohub-data-undp-org-2024-10-16-09_22_01](https://github.com/user-attachments/assets/6493e6d9-1b8e-445f-b67a-c5cafdfb758d)

### Mockup URL/file

[Review of landing pages (benchmark analysis)](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3794-6447)

**Comment by balagurova** [comment]
An old link (2023) to the [content of the GeoHub page on DFx](https://undp-my.sharepoint.com/:w:/r/personal/anastasiia_balagurova_undp_org/Documents/GeoHub%20Page%20Content.docx?d=wb31297a81c7c4b17805e0ae0fcd5ff10&csf=1&web=1&e=Dlcp0P)

**Comment by balagurova** [comment]
@JinIgarashi @iferencik @Thuhaa 
Hi! Sharing a document with questions](https://undp-my.sharepoint.com/personal/anastasiia_balagurova_undp_org/_layouts/15/doc.aspx?sourcedoc=%7Bbf8b959c-988c-4d15-b2db-f67ca463c0c5%7D&action=edit). Please feel free to add any thoughts / ideas there

**Comment by balagurova** [comment]
@JinIgarashi @iferencik @Thuhaa 
Here is a current mockup for the landing page: [Figma](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3790-5304)
Please review and let me know if anything is not clear or any edits are needed

**Comment by JinIgarashi** [comment]
@balagurova I commented on your figma mockup

**Comment by balagurova** [comment]
@JinIgarashi thanks! I have addressed these aspects, let's discuss the updated mockup next week:
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3790-5304

**Comment by balagurova** [comment]
@JinIgarashi hi! overall it looks almost perfect! Here are some small things to fix:

1) a typo in the breadcrumbs: 'Data Futures Exchange"
<img width="455" alt="Image" src="https://github.com/user-attachments/assets/4627c599-5d8a-489e-aed1-11a3deee3d9e" />

2) This section has different margins than the previous one, please align with others:
<img width="1695" alt="Image" src="https://github.com/user-attachments/assets/1129c157-772d-4d93-8570-c1faef5f10d2" />


3) The margin here is missing, in another section it is 32px in the same element:
<img width="1010" alt="Image" src="https://github.com/user-attachments/assets/90cd6254-fad7-4171-bdb8-7cc884543899" />

<img width="1614" alt="Image" src="https://github.com/user-attachments/assets/b5988c21-2da5-4639-b4b8-fda063337afd" />



4) In this CTA block please change paddings to 'padding: 96px 144px;' and also update the button. 
<img width="1690" alt="Image" src="https://github.com/user-attachments/assets/1d56d8b2-648a-406c-b83d-c20c41375fdf" />

A reference for paddings and a red button can be this:
<img width="1568" alt="Image" src="https://github.com/user-attachments/assets/433a963e-03ef-4b8b-88df-580ec5775b9d" />

5) Please remove the margin on the right here so that the text takes all the space of the container:
<img width="1668" alt="Image" src="https://github.com/user-attachments/assets/e39e6941-2948-4b1a-b074-3d695488da92" />

6) Please change the padding-top from 16px to 24px here. 16px is used when we have a small tag, when we don't have it, it's better to have a bit more space.
<img width="565" alt="Image" src="https://github.com/user-attachments/assets/2d7f156b-79d6-4d2f-bc57-7976a708f4bc" />

7) It would be nice to add a non-breakable space within the title text between "for" and "supporting" – just copy this text and it should be there: "open-source geospatial services for supporting SDG development" so that it looks like this:
<img width="814" alt="Image" src="https://github.com/user-attachments/assets/9d6ecc93-2f18-419f-b06a-0001a87aa582" />
and not like this:
<img width="886" alt="Image" src="https://github.com/user-attachments/assets/0497c1cd-f15b-4735-9699-88395d82d965" />


btw mobile version looks really nice!

**Comment by balagurova** [comment]
@JinIgarashi Hi! Looks really good, but there are some small issues with a few things:

1) New block with a slider: there's a responsiveness issue in the new slider block:
<img width="1674" alt="Image" src="https://github.com/user-attachments/assets/269edea4-ff99-4c7e-a3a5-bd84093fc797" />

Here are the necessary changes:
– Ensure one slide takes up the entire width, and the image occupies 65% of the slide:
<img width="1669" alt="Image" src="https://github.com/user-attachments/assets/da24b431-5690-4a5f-965b-54794b3c84e5" />
– Move the navigation arrows to the right side so they don't hang in the middle of the block:
<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/ce0ff969-d518-47ad-89c5-f0094534a75e" />
– Remove the 44px padding-right to make the slider and scrollbar take up the full width:
<img width="1667" alt="Image" src="https://github.com/user-attachments/assets/c1957a5c-90cb-43f8-8e41-17b049afcf70" />
– Please update the images for the CEEI and Electricity Dashboards: here:https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=4025-4336&t=xaKfouKs8W0psjDC-1 

2) The section with solutions should have a light-gray background (please have a look a mockup in Figma) to make sections differentiate from each other. The quick solution for this would be just to change margin to padding with the same values and add background gray-200. 

3) The button in the CTA block looks different than in another similar block.
<img width="1107" alt="Image" src="https://github.com/user-attachments/assets/0c065c5e-63da-414a-8df6-18dbd2868158" />
 It should match the size of the left button in this example:
<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/27036738-728b-4b14-96e8-8b19e6bcba8a" />

4) My mistake here—please adjust the margins at the top and bottom of this block to 32px for consistency:
<img width="941" alt="Image" src="https://github.com/user-attachments/assets/6fcc89ea-1fa7-422e-8969-ec5897d521b7" />

5) I've looked at the tools blocks that you've added and I think the 4 column layout looks a bit better and compact in terms of height. Let's introduce it to the maps and storymaps as well:
<img width="1655" alt="Image" src="https://github.com/user-attachments/assets/f0c6e205-3cf8-45d6-ade8-a5a28449256e" />

**Comment by balagurova** [comment]
@JinIgarashi I've also checked the mobile version and there is a couple of things as well:


1) A slider block has some responsiveness issues:
- the image goes to the left edge of the screen:
<img width="468" alt="Image" src="https://github.com/user-attachments/assets/16a84226-0e9c-434e-8fb8-641e965e0be2" />

- no arrows are visible:
<img width="557" alt="Image" src="https://github.com/user-attachments/assets/3ff70bf6-1f03-42dc-9063-4278f17f65e5" />

2) There are some inconsistencies in margins/padding on the left and right edges (some of them are due to my mistake in the mockups, sorry). Let's keep **16px** as a universal spacing for the left and right edges and apply it consistently across all sections/blocks.

3) please remove this margin-left from the h3 elements because the section already has 16px padding:
<img width="498" alt="Image" src="https://github.com/user-attachments/assets/edd06489-cf4e-4d7d-8a7f-024408999c74" />

3) spacing between text and demo is missing here:
<img width="395" alt="Image" src="https://github.com/user-attachments/assets/27372248-dd1f-4438-8bd6-b25b9505fd7b" />

**Comment by JinIgarashi** [comment]
> no arrows are visible:

I found in UNDP carousel, no arrow buttons are shown in mobile, instead it constantly shows slider.

**Comment by balagurova** [comment]
@JinIgarashi Hi! Everything looks great, except for one small issue on the mobile version: the scrollbar stretches from edge to edge, but it would be better if it had a 16px padding to match the other elements.
<img width="434" alt="Image" src="https://github.com/user-attachments/assets/d3040f64-ed69-4596-84ab-cd5f0bbf0aa9" />
