### ISSUE TITLE
The sampling method might work suboptimally

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#4315]
### Refactoring Description

Geohub uses histogram  sampling instead of reading all attribute data whenever classification is performed on the raster or vector layers. It looks like this method does not work optimally with some data(too few values perhaps).

Ideally a threshold vakue should be set where below that threshold real data is read and above it the hist sampling is used. Alternatively the sampling needs tro be improved

### Refacotring components

classification method

### Refactoring Implementation

improve sampling or use threshold

**Comment by JinIgarashi** [comment]
current function to make sample for classification is only consider min/max and classification method.

https://github.com/UNDP-Data/geohub/blob/ff3314e987465cceb0233d12acbb357fcf7e1cbb/sites/geohub/src/lib/helper/getSampleFromInterval.ts#L3-L15

It ignores actual data distribution to make sample randomly. maybe equidistant may work with this method, however quantile and natural break and logarithmic might not work. I think generating sampled values by considering actual data distribution like histogram is needed.
