### ISSUE TITLE
[UI/UX] Share/Save behaviour of Map Editor

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#4439]
### Description

Current button and dialog design are not intuitive and confusing. It needs to be improved.

The behaviour of sharing/saving feature can be differentiate by the following conditions:
- If user is the owner/editor of the map
- If user is not owner/editor of the map (maybe disable saving feature at all? Users use duplicate button (will be implemented by #4437) to change existing map style as their own map?)

## Current screenshot

- Share/Save dialog

![image](https://github.com/user-attachments/assets/ad0b79cd-5058-496d-a391-73d751007c73)

- When users leave map after changing map state

![image](https://github.com/user-attachments/assets/db3a8fff-a6d7-4211-9ca1-517386064189)

**Comment by balagurova** [comment]
@JinIgarashi Hi, this is [a current Figma mockup](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3826-6896). I'll update it in a couple of days with icons for the map.

**Comment by balagurova** [comment]
Hi, three small suggestions for this popup:
<img width="754" alt="image" src="https://github.com/user-attachments/assets/b37bc942-5a1a-4eb0-8c6f-47558d0c0a93">

1) Let's rename 'Close and Continue' to 'Stay on Map' – the current wording might be confusing for users. It's unclear what 'Close' refers to (the popup? the entire page?) or what 'Continue' means (continue to a new page? continue editing the map?)

2) Let's keep the primary button red and change the secondary button to grey. This will emphasize the main action and create a clear visual hierarchy between the two buttons: 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/a1b219ff-dfc2-4120-b438-02a0aa169f5d">


3) I would add the message as a simple paragraph element without highlighting it with a yellow alert background, as it is the only message on the page and doesn't need extra emphasis: 
<img width="801" alt="image" src="https://github.com/user-attachments/assets/61bc6441-c8e3-4194-b731-8bdf6cda9b50">

**Comment by balagurova** [comment]
One small suggestion for the share button: it looks great, and the placement works well! I’d just add a tooltip for the disabled state to clarify why it’s inactive, something like, 'You need to save the map first to enable sharing.' This would make it clear to users why the button is disabled
<img width="441" alt="image" src="https://github.com/user-attachments/assets/6b1d2a0d-5279-4629-a71b-4d791dfd1098">

**Comment by JinIgarashi** [comment]
> One small suggestion for the share button: it looks great, and the placement works well! I’d just add a tooltip for the disabled state to clarify why it’s inactive, something like, 'You need to save the map first to enable sharing.' This would make it clear to users why the button is disabled

I can add tooltip for button, but I realized tippyjs does not show tooltip when button is disabled. that means we cannot show tooltip for disabled buttons.

**Comment by JinIgarashi** [comment]
ah, I found a way to show tippy by wrapping button element
