### ISSUE TITLE
fix missing checkbox in colormap card

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#671]
The colormap card

![image](https://user-images.githubusercontent.com/92793531/195323514-c50bba9f-b47c-4841-8604-ac656aac3e1a.png)

contains an check icon which should be visible when a specific colormap is selected/active

[chcek here](https://github.com/UNDP-Data/geohub/blob/develop/src/components/ColorMapPickerCard.svelte#L39-L43) to check the source code

**Comment by JinIgarashi** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/2639701/195898811-2a25e7a6-706b-4f5b-93b4-bc44fdfb8e39.png">

Is it already shown correctly?
