### ISSUE TITLE
id is required for all vector tile source to introduce feature state

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#725]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2639701/197775682-fb9ed98c-c601-44e8-a790-b4283323d0e0.png)

currently, all vector tiles source in geohub is missing `id` as shown in the above screenshot. We need `id` in the top level of each GeoJSON feature in order to implement FeatureState to highlight the feature by hovering or clicking.

- FeatureState guide by Mapbox
https://blog.mapbox.com/going-live-with-electoral-maps-a-guide-to-feature-state-b520e91a22d

alternatively, there is a way to use `promoteId` in style.json to implement FeatureState, but this can be difficult because Geohub cannot have style.json in advance.

- promoteId spec
https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#vector-promoteId

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201782076) by [Unito](https://www.unito.io)

**Comment by iferencik** [comment]
this is not required anymore
