### ISSUE TITLE
point DB from old to new

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#733]
GeoHub uses a new PostGres DB server that is much more powerful and fast.
The schema&table were migrated to the new server  from old one under the exact same names/rights
In order to use the new DB it should be tested  from a local dev env and the GH secret needs to be updated.

**Comment by JinIgarashi** [comment]
`DATABASE_CONNECTION` in Github secret was now updated. The app will be connecting to new PostGIS when next deployment will be done.
