### ISSUE TITLE
fix bugs related the state of tags after a tag is removed

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#925]
![image](https://user-images.githubusercontent.com/92793531/206467430-c70d1693-e2d6-41f1-9fef-8d2ae7e760e5.png)

when the keword is removed the UI should go to Home not show the layer list

![image](https://user-images.githubusercontent.com/92793531/206470007-ac452f46-3899-4f29-b733-966d8564d689.png)

additionally, the selected tag does not reset the state of the filter component

![image](https://user-images.githubusercontent.com/92793531/206470493-cfc34654-c352-4186-a3f0-fa774b8ff03e.png)

 after removing the tag the component is not reset

![image](https://user-images.githubusercontent.com/92793531/206470682-d454c99a-139a-4fcc-ac9b-108c0df476bd.png)

**Comment by JinIgarashi** [comment]
this is now solved
